services:
  mongo:
    build:
      context: ./backend
      dockerfile: Dockerfile.Mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  app:
    build:
      context: ./opa-suite
      dockerfile: Dockerfile     
    ports:
      - "8080:80"
    volumes:
      - frontend_build:/app/build
    env_file:
      - ./opa-suite/.env
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_db:
  frontend_build: