services:
  mongo:
    build:
      context: ./backend
      dockerfile: Dockerfile.Mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  app:
    build:
      context: ./opa-suite
      dockerfile: Dockerfile     
      args:
        NEXT_PUBLIC_API_URL_BASE: ${NEXT_PUBLIC_API_URL_BASE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - frontend_build:/app/build
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL_BASE=${NEXT_PUBLIC_API_URL_BASE}
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file:
      - .env
    environment:
      - PORT=${PORT_BACKEND}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_db:
  frontend_build: