services:
  app:
    build:
      context: ./opa-suite
      dockerfile: Dockerfile     
      args:
        NEXT_PUBLIC_API_URL_BASE: ${NEXT_PUBLIC_API_URL_BASE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - frontend_build:/app/build
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL_BASE=${NEXT_PUBLIC_API_URL_BASE}
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file:
      - .env
    environment:
      - PORT=${PORT_BACKEND}
    restart: unless-stopped
    networks:
      - app_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_db:
  frontend_build: