
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "../styles/globals.css";
import { AuthProvider } from "@/context/AutContext";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <body
        className={`${poppins.className} ${poppins.className}  `}
      >

        <AuthProvider>
          {children}
          <Toaster richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
